# Generated by Django 3.2.5 on 2022-02-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetables'), ('RF', 'Raw Food'), ('S', 'Spices')], max_length=2),
        ),
    ]
