# Generated by Django 4.0.2 on 2022-03-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Courier Agent', 'Courier Agent')], default='Customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetables'), ('RF', 'RawFood'), ('S', 'Spices')], max_length=2),
        ),
    ]
